pages:
  stage: deploy
  script:
    - mkdir .dist
    - cp -r ./* .dist
    - rm -rf dist
    - mv .dist dist
  artifacts:
    paths:
      - dist
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
